#!/bin/bash

user="imo059"

errors=(
"CRITICAL: Node compute-01 unreachable (user=$user)"
"FATAL: Job 10342 submitted by $user exceeded walltime and was terminated"
"ERROR: MPI rank 12 for $user failed with signal 11 (Segmentation fault)"
"ALERT: GPU device 0 on node gpu-04 overheated – job owner $user"
"PANIC: Slurmctld: unable to write state save file for user $user"
"CRITICAL: Lustre filesystem /scratch quota exceeded by $user"
"ERROR: Out of memory on node mem-08 – cgroup killed $user’s process"
"WARNING: Duplicate SSH keys detected for $user – possible security issue"
"ALERT: Network partition detected, jobs for $user may stall"
"FATAL: Storage-node-03 I/O error – job data lost for $user"
"CRITICAL: Node compute-07 kernel panic – user=$user jobs aborted"
"ERROR: Job 84213 owned by $user terminated abnormally – exit code 137"
"PANIC: Infiniband link failure, 23 ranks for $user isolated"
"WARNING: $user attempted to access restricted partition – denied"
"FATAL: Checkpoint restart failed – data corrupted for $user"
"ALERT: GPU 2 ECC errors exceeded threshold – job owner $user killed"
"ERROR: Slurm job step creation failed (user=$user)"
"CRITICAL: RAID controller degraded – metadata loss affecting $user"
"WARNING: Disk latency spike detected, $user IO throttled"
"FATAL: Job database corruption – unable to update record for $user"
"ERROR: Segmentation fault (core dumped) – user=$user job rank 244"
"CRITICAL: Node compute-17 lost heartbeat – $user tasks terminated"
"WARNING: $user exceeded max memory limit, process killed by OOM killer"
"ALERT: High CPU temperature on node cpu-12 – user=$user job paused"
"FATAL: Network timeout communicating with node net-02 – user=$user"
"ERROR: Lustre lock timeout – $user jobs may hang"
"CRITICAL: Job array submission failed for $user – quota exceeded"
"WARNING: Slurm backfill scheduler skipped $user jobs – insufficient resources"
"ALERT: Job preemption triggered – $user job stopped"
"FATAL: License server not responding – $user job cannot start"
"ERROR: Application error: illegal instruction – job owner $user"
"CRITICAL: Storage space exhausted on /work – $user writes failed"
"WARNING: $user attempted to submit >1000 jobs – throttled"
"PANIC: Orphaned job step detected – cleaning up $user session"
"ALERT: GPU memory leak suspected in job by $user"
"FATAL: Compute node compute-19 overheating – $user job evacuated"
"ERROR: Failed to mount /scratch for $user – input/output error"
"CRITICAL: Node gpu-11 reset unexpectedly – job owner $user impacted"
"WARNING: $user exceeded max open file descriptors – job unstable"
"ALERT: Scheduler backlog exceeded 100k jobs, $user submission delayed"
"PANIC: Kernel panic on storage-node-05 – $user’s files may be corrupt"
"ERROR: MPI timeout – $user rank 77 failed to respond"
"CRITICAL: Job 55123 for $user exceeded node memory, aborted"
"WARNING: Disk quota check failed for $user – inconsistent state"
"FATAL: System log corruption detected – affecting $user jobs"
"ALERT: Infiniband congestion on fabric – user=$user jobs degraded"
"ERROR: Slurmctld RPC error – unable to allocate resources for $user"
"CRITICAL: Node compute-31 BIOS error – shutting down, jobs for $user lost"
"WARNING: GPU driver crash – $user kernels reset"
"FATAL: Power supply failure on node psu-07 – user=$user job interrupted"
"ERROR: Application core dump size exceeded for $user – truncated"
"CRITICAL: Job checkpoint disk full – $user data discarded"
"WARNING: Lustre OST down – $user writes pending"
"ALERT: $user job preempted by high priority queue"
"FATAL: Node compute-22 hit thermal shutdown – $user job stopped"
"ERROR: Invalid CUDA version in $user job environment"
"CRITICAL: Inconsistent job state – cleanup required for $user"
"WARNING: Shared memory exhausted – $user jobs throttled"
"ALERT: $user exceeded max simultaneous jobs – new submissions blocked"
"PANIC: Job step ID mismatch – user=$user session terminated"
"FATAL: RAID rebuild stalled – risk of data loss for $user"
"ERROR: Illegal memory access in GPU kernel – job owner $user"
"CRITICAL: Timeout waiting for node compute-45 – $user jobs aborted"
"WARNING: Job priority inversion detected – $user delayed"
"ALERT: Job 99231 exceeded max runtime – terminated (user=$user)"
"ERROR: Communication error between ranks – user=$user MPI job hung"
"CRITICAL: Scheduler failover unsuccessful – jobs for $user impacted"
"WARNING: Disk errors on storage-node-09 – $user IO retried"
"FATAL: License checkout failed – $user job cannot proceed"
"ALERT: Infiniband adapter reset – $user job performance degraded"
"ERROR: Python traceback in $user’s job – ValueError encountered"
"CRITICAL: Compute node compute-53 low memory – killing $user processes"
"WARNING: Job output truncated – $user logs incomplete"
"ALERT: $user attempted to allocate more GPUs than available – denied"
"FATAL: Job script syntax error detected for $user – submission failed"
"ERROR: Network packet loss >10% – $user jobs unstable"
"CRITICAL: Metadata corruption on Lustre MDS – user=$user impacted"
"WARNING: Job $user exceeded IOPS limit – throttled"
"ALERT: GPU overcurrent detected – $user device disabled"
"FATAL: Slurmdbd crashed – unable to record $user accounting"
"ERROR: Application hang detected – $user job force-killed"
"CRITICAL: Node compute-61 offline – $user jobs rescheduled"
"WARNING: File handle leak detected in $user job"
"ALERT: Checkpoint restore failed – $user lost 12h of progress"
"FATAL: Kernel panic on gpu-18 – terminating $user session"
"CORE DUMPED"
)


{
  for err in "${errors[@]}"; do
    echo "$err"
    sleep 0.3   # 1 sekund pause mellom linjene
  done
} | write "$user"
# } | wall

